{
 "title": "PaaS Exporter",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "organisation", "query": { "query": "label_values(organisation)" } },
   { "name": "space", "query": { "query": "label_values(space)" } },
   { "name": "app", "query": { "query": "label_values(app)" } }
  ]
 },
 "panels": [
  {
   "title": "Disk $space",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "space",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Disk utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "disk_utilization{organisation=~\"$organisation\", space=~\"$space\", app=~\"$app\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory $space",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "repeat": "space",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "memory_utilization{organisation=~\"$organisation\", space=~\"$space\", app=~\"$app\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU $space",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "repeat": "space",
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "cpu{organisation=~\"$organisation\", space=~\"$space\", app=~\"$app\"}"
    }
   ]
  }
 ]
}